import type { Metadata } from "next";

import "./globals.css";
import Navbar from "./componants/navbar/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <Navbar />
        <div className=" sm:w-full md:w-[80%] lg:w-[80%] m-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
